In [2]:
import pandas as pd

In [3]:
fives = pd.read_csv('../data/2025s.csv')
df = fives.copy()

In [4]:
df[['Club Gym', 'State']] = df['Gym'].str.extract(r'^(.*?)\s*\((\w+)\)$')
df['Club Gym'] = df['Club Gym'].fillna(df['Gym'])

In [5]:
df['Region'] = df['Region'].apply(lambda x: x[1:] if isinstance(x,str) and x.startswith('R') else x)

In [6]:
df.head()

,Athlete,DOB,Gym,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State
0,Merideth Brandt,04/08/2007,Yellow Jackets (MA),6,Nebraska,10-2024,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/meridethbrandtgymnas...,https://www.instagram.com/merideth.brandt/,Yellow Jackets,MA
1,Shyla Bhatia,07/02/2007,Silvia's (PA),7,Denver,10-2024,9.775,9.575,9.425,9.850,38.35,https://www.instagram.com/shylabhatia2025/,https://www.instagram.com/missy_miss_demeaner/,Silvia's,PA
2,Sevana Kasparian,07/25/2007,Gymnastics Olympica (CA),1,Denver,10-2025,9.7,9.825,9.600,9.700,38.275,https://www.instagram.com/sevanakasparian2025/,NaN,Gymnastics Olympica,CA
3,Mckenzie Matters,01/08/2007,Prestige (PA),7,Alabama,10-2024,9.8,9.7,9.725,9.825,39,https://www.instagram.com/mckenzie.matters_2025/,https://www.instagram.com/mckenzie.matters/,Prestige,PA
4,Addison Bare,10/10/2006,Prestige (PA),7,Arkansas,10-2024,9.675,9.725,9.700,9.650,38.575,https://www.instagram.com/addisonbare.gym2025/,https://www.instagram.com/addisonbaree/,Prestige,PA

In [7]:
df[['Level', 'Year']] = df['Level'].str.extract(r'^([A-Za-z0-9]+)-(\d{4})$')

In [8]:
df.head()

,Athlete,DOB,Gym,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State,Year
0,Merideth Brandt,04/08/2007,Yellow Jackets (MA),6,Nebraska,10,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/meridethbrandtgymnas...,https://www.instagram.com/merideth.brandt/,Yellow Jackets,MA,2024
1,Shyla Bhatia,07/02/2007,Silvia's (PA),7,Denver,10,9.775,9.575,9.425,9.850,38.35,https://www.instagram.com/shylabhatia2025/,https://www.instagram.com/missy_miss_demeaner/,Silvia's,PA,2024
2,Sevana Kasparian,07/25/2007,Gymnastics Olympica (CA),1,Denver,10,9.7,9.825,9.600,9.700,38.275,https://www.instagram.com/sevanakasparian2025/,NaN,Gymnastics Olympica,CA,2025
3,Mckenzie Matters,01/08/2007,Prestige (PA),7,Alabama,10,9.8,9.7,9.725,9.825,39,https://www.instagram.com/mckenzie.matters_2025/,https://www.instagram.com/mckenzie.matters/,Prestige,PA,2024
4,Addison Bare,10/10/2006,Prestige (PA),7,Arkansas,10,9.675,9.725,9.700,9.650,38.575,https://www.instagram.com/addisonbare.gym2025/,https://www.instagram.com/addisonbaree/,Prestige,PA,2024

In [9]:
six = pd.read_csv('../data/2026s.csv')
sev = pd.read_csv('../data/2027s.csv')

df_six = six.copy()
df_sev = sev.copy()

In [10]:
df_six.head()

,Athlete,DOB,Gym,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta
0,Olivia Gigliotti,NaN,Manjaks,I-Canada,Uncommitted,9-2025,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/olivia.gigliotti_gym/,https://www.instagram.com/olivia_b.gigliotti/
1,Sammie Shein,10/12/2007,Nova Elite (WA),R2,Uncommitted,8-2024,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/sshein_gymnast26/,https://www.instagram.com/sammieshein/
2,Sienna Livengood,09/11/2007,Metro (OR),R2,Uncommitted,9-2024,9.15,9.350,9.40,9.600,36.90,NaN,https://www.instagram.com/siennaxo.7/
3,Kylie Saunders,NaN,Inspire (WA),R2,Uncommitted,9-2024,8.40,7.325,8.55,8.625,32.45,https://www.instagram.com/kylie_saunders2026/,https://www.instagram.com/kylie_7228/
4,Hadley Whited,NaN,Helena (MT),R2,Uncommitted,9-2024,9.20,8.650,8.20,9.300,34.55,NaN,https://www.instagram.com/whited_hadley/

In [11]:
df_six[['Club Gym', 'State']] = df_six['Gym'].str.extract(r'^(.*?)\s*\((\w+)\)$')
df_six['Club Gym'] = df_six['Club Gym'].fillna(df_six['Gym'])
df_six['Region'] = df_six['Region'].apply(lambda x: x[1:] if isinstance(x,str) and x.startswith('R') else x)
df_six[['Level', 'Year']] = df_six['Level'].str.extract(r'^([A-Za-z0-9]+)-(\d{4})$')

In [12]:
df_six.head()

,Athlete,DOB,Gym,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State,Year
0,Olivia Gigliotti,NaN,Manjaks,I-Canada,Uncommitted,9,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/olivia.gigliotti_gym/,https://www.instagram.com/olivia_b.gigliotti/,Manjaks,NaN,2025
1,Sammie Shein,10/12/2007,Nova Elite (WA),2,Uncommitted,8,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/sshein_gymnast26/,https://www.instagram.com/sammieshein/,Nova Elite,WA,2024
2,Sienna Livengood,09/11/2007,Metro (OR),2,Uncommitted,9,9.15,9.350,9.40,9.600,36.90,NaN,https://www.instagram.com/siennaxo.7/,Metro,OR,2024
3,Kylie Saunders,NaN,Inspire (WA),2,Uncommitted,9,8.40,7.325,8.55,8.625,32.45,https://www.instagram.com/kylie_saunders2026/,https://www.instagram.com/kylie_7228/,Inspire,WA,2024
4,Hadley Whited,NaN,Helena (MT),2,Uncommitted,9,9.20,8.650,8.20,9.300,34.55,NaN,https://www.instagram.com/whited_hadley/,Helena,MT,2024

In [13]:
df_sev.head()

,Athlete,DOB,Region,Gym,School,Level,Instagram-gym,instagram-personal,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta
0,Mckenna Trolio,05/29/2008,R5,Olympic Dreams (OH),Uncommitted,9-2025,https://www.instagram.com/gymnast_mckenna__4life/,Personal,9.425,9.35,9.5,9.525,36.725,https://www.instagram.com/gymnast_mckenna__4life/,NaN
1,Cassandra Principe,NaN,I-Canada,Calgary Gymnastics Centre,Uncommitted,10-2023,https://www.instagram.com/cassprincipe_gym2027/,NaN,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/cassprincipe_gym2027/,NaN
2,Anika Spence,NaN,I-Canada,Gymnastics Mississauga,Uncommitted,9,https://www.instagram.com/anikaspence.2027/,Personal,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/anikaspence.2027/,NaN
3,Riley Monsour,NaN,I-Canada,Futures,Uncommitted,8-2024,https://www.instagram.com/rileymonsour_2027/,NaN,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/rileymonsour_2027/,NaN
4,Ashleigh Rose Evans,Insta,I-UK,Clwb Cymru Caerdydd,Uncommitted,E-2024,https://www.instagram.com/ashleigh_evans_09/,https://www.instagram.com/ashleigh_rose.e/,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/ashleigh_evans_09/,https://www.instagram.com/ashleigh_rose.e/

In [14]:
df_sev[['Club Gym', 'State']] = df_sev['Gym'].str.extract(r'^(.*?)\s*\((\w+)\)$')
df_sev['Club Gym'] = df_sev['Club Gym'].fillna(df_sev['Gym'])
df_sev['Region'] = df_sev['Region'].apply(lambda x: x[1:] if isinstance(x,str) and x.startswith('R') else x)
df_sev[['Level', 'Year']] = df_sev['Level'].str.extract(r'^([A-Za-z0-9]+)-(\d{4})$')

In [15]:
df_sev.head()

,Athlete,DOB,Region,Gym,School,Level,Instagram-gym,instagram-personal,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State,Year
0,Mckenna Trolio,05/29/2008,5,Olympic Dreams (OH),Uncommitted,9,https://www.instagram.com/gymnast_mckenna__4life/,Personal,9.425,9.35,9.5,9.525,36.725,https://www.instagram.com/gymnast_mckenna__4life/,NaN,Olympic Dreams,OH,2025
1,Cassandra Principe,NaN,I-Canada,Calgary Gymnastics Centre,Uncommitted,10,https://www.instagram.com/cassprincipe_gym2027/,NaN,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/cassprincipe_gym2027/,NaN,Calgary Gymnastics Centre,NaN,2023
2,Anika Spence,NaN,I-Canada,Gymnastics Mississauga,Uncommitted,NaN,https://www.instagram.com/anikaspence.2027/,Personal,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/anikaspence.2027/,NaN,Gymnastics Mississauga,NaN,NaN
3,Riley Monsour,NaN,I-Canada,Futures,Uncommitted,8,https://www.instagram.com/rileymonsour_2027/,NaN,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/rileymonsour_2027/,NaN,Futures,NaN,2024
4,Ashleigh Rose Evans,Insta,I-UK,Clwb Cymru Caerdydd,Uncommitted,E,https://www.instagram.com/ashleigh_evans_09/,https://www.instagram.com/ashleigh_rose.e/,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/ashleigh_evans_09/,https://www.instagram.com/ashleigh_rose.e/,Clwb Cymru Caerdydd,NaN,2024

In [16]:
df_six.head()

,Athlete,DOB,Gym,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State,Year
0,Olivia Gigliotti,NaN,Manjaks,I-Canada,Uncommitted,9,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/olivia.gigliotti_gym/,https://www.instagram.com/olivia_b.gigliotti/,Manjaks,NaN,2025
1,Sammie Shein,10/12/2007,Nova Elite (WA),2,Uncommitted,8,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/sshein_gymnast26/,https://www.instagram.com/sammieshein/,Nova Elite,WA,2024
2,Sienna Livengood,09/11/2007,Metro (OR),2,Uncommitted,9,9.15,9.350,9.40,9.600,36.90,NaN,https://www.instagram.com/siennaxo.7/,Metro,OR,2024
3,Kylie Saunders,NaN,Inspire (WA),2,Uncommitted,9,8.40,7.325,8.55,8.625,32.45,https://www.instagram.com/kylie_saunders2026/,https://www.instagram.com/kylie_7228/,Inspire,WA,2024
4,Hadley Whited,NaN,Helena (MT),2,Uncommitted,9,9.20,8.650,8.20,9.300,34.55,NaN,https://www.instagram.com/whited_hadley/,Helena,MT,2024

In [17]:
df_sev.drop(columns=['Gym', 'Instagram-gym', 'instagram-personal'], inplace=True)

In [18]:
df_six.drop(columns=['Gym'], inplace=True)

In [19]:
df.head()
df.drop(columns=['Gym'], inplace=True)

In [20]:
df.head()

,Athlete,DOB,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State,Year
0,Merideth Brandt,04/08/2007,6,Nebraska,10,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/meridethbrandtgymnas...,https://www.instagram.com/merideth.brandt/,Yellow Jackets,MA,2024
1,Shyla Bhatia,07/02/2007,7,Denver,10,9.775,9.575,9.425,9.850,38.35,https://www.instagram.com/shylabhatia2025/,https://www.instagram.com/missy_miss_demeaner/,Silvia's,PA,2024
2,Sevana Kasparian,07/25/2007,1,Denver,10,9.7,9.825,9.600,9.700,38.275,https://www.instagram.com/sevanakasparian2025/,NaN,Gymnastics Olympica,CA,2025
3,Mckenzie Matters,01/08/2007,7,Alabama,10,9.8,9.7,9.725,9.825,39,https://www.instagram.com/mckenzie.matters_2025/,https://www.instagram.com/mckenzie.matters/,Prestige,PA,2024
4,Addison Bare,10/10/2006,7,Arkansas,10,9.675,9.725,9.700,9.650,38.575,https://www.instagram.com/addisonbare.gym2025/,https://www.instagram.com/addisonbaree/,Prestige,PA,2024

In [21]:
df_sev.head()

,Athlete,DOB,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State,Year
0,Mckenna Trolio,05/29/2008,5,Uncommitted,9,9.425,9.35,9.5,9.525,36.725,https://www.instagram.com/gymnast_mckenna__4life/,NaN,Olympic Dreams,OH,2025
1,Cassandra Principe,NaN,I-Canada,Uncommitted,10,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/cassprincipe_gym2027/,NaN,Calgary Gymnastics Centre,NaN,2023
2,Anika Spence,NaN,I-Canada,Uncommitted,NaN,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/anikaspence.2027/,NaN,Gymnastics Mississauga,NaN,NaN
3,Riley Monsour,NaN,I-Canada,Uncommitted,8,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/rileymonsour_2027/,NaN,Futures,NaN,2024
4,Ashleigh Rose Evans,Insta,I-UK,Uncommitted,E,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/ashleigh_evans_09/,https://www.instagram.com/ashleigh_rose.e/,Clwb Cymru Caerdydd,NaN,2024

In [22]:
df['Class'] = 2025
df_six['Class'] = 2026
df_sev['Class'] = 2027

In [23]:
df_sev.head()

,Athlete,DOB,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State,Year,Class
0,Mckenna Trolio,05/29/2008,5,Uncommitted,9,9.425,9.35,9.5,9.525,36.725,https://www.instagram.com/gymnast_mckenna__4life/,NaN,Olympic Dreams,OH,2025,2027
1,Cassandra Principe,NaN,I-Canada,Uncommitted,10,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/cassprincipe_gym2027/,NaN,Calgary Gymnastics Centre,NaN,2023,2027
2,Anika Spence,NaN,I-Canada,Uncommitted,NaN,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/anikaspence.2027/,NaN,Gymnastics Mississauga,NaN,NaN,2027
3,Riley Monsour,NaN,I-Canada,Uncommitted,8,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/rileymonsour_2027/,NaN,Futures,NaN,2024,2027
4,Ashleigh Rose Evans,Insta,I-UK,Uncommitted,E,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/ashleigh_evans_09/,https://www.instagram.com/ashleigh_rose.e/,Clwb Cymru Caerdydd,NaN,2024,2027

In [24]:
df_all = pd.concat([df, df_six, df_sev], ignore_index=True)

In [26]:
df_all.head()

,Athlete,DOB,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State,Year,Class
0,Merideth Brandt,04/08/2007,6,Nebraska,10,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/meridethbrandtgymnas...,https://www.instagram.com/merideth.brandt/,Yellow Jackets,MA,2024,2025
1,Shyla Bhatia,07/02/2007,7,Denver,10,9.775,9.575,9.425,9.850,38.35,https://www.instagram.com/shylabhatia2025/,https://www.instagram.com/missy_miss_demeaner/,Silvia's,PA,2024,2025
2,Sevana Kasparian,07/25/2007,1,Denver,10,9.7,9.825,9.600,9.700,38.275,https://www.instagram.com/sevanakasparian2025/,NaN,Gymnastics Olympica,CA,2025,2025
3,Mckenzie Matters,01/08/2007,7,Alabama,10,9.8,9.7,9.725,9.825,39,https://www.instagram.com/mckenzie.matters_2025/,https://www.instagram.com/mckenzie.matters/,Prestige,PA,2024,2025
4,Addison Bare,10/10/2006,7,Arkansas,10,9.675,9.725,9.700,9.650,38.575,https://www.instagram.com/addisonbare.gym2025/,https://www.instagram.com/addisonbaree/,Prestige,PA,2024,2025

In [27]:
df_all['Country'] = df_all['State'].apply(lambda x: 'USA' if pd.notna(x) else 'International')

In [28]:
df_all['Level'].unique()

array(['10', 'e', 'E', nan, '9', 'HS', '8', 'XSA', 'XD', 'DN', 'xsa',
       'XS', 'xd', 'XP', 'xp', 'H', 'hs', '6', '7'], dtype=object)

In [29]:
df_all['Level'] = df_all['Level'].str.strip().str.upper()

In [30]:
df_all['Level'] = df_all['Level'].replace({'E': 'Elite'})

In [31]:
print(df_all['Level'].unique())

['10' 'Elite' nan '9' 'HS' '8' 'XSA' 'XD' 'DN' 'XS' 'XP' 'H' '6' '7']

In [32]:
df_all['IsElite'] = df_all['Level'] == 'Elite'

In [33]:
df_all['IsElite'] = df_all['Level'] == 'Elite'

In [34]:
score_cols = ['VT High', 'UB High', 'BB High', 'FX High', 'AA High']
df_all[score_cols] = df_all[score_cols].apply(pd.to_numeric, errors='coerce')

In [35]:
df_all.head()

,Athlete,DOB,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State,Year,Class,Country,IsElite
0,Merideth Brandt,04/08/2007,6,Nebraska,10,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/meridethbrandtgymnas...,https://www.instagram.com/merideth.brandt/,Yellow Jackets,MA,2024,2025,USA,False
1,Shyla Bhatia,07/02/2007,7,Denver,10,9.775,9.575,9.425,9.850,38.350,https://www.instagram.com/shylabhatia2025/,https://www.instagram.com/missy_miss_demeaner/,Silvia's,PA,2024,2025,USA,False
2,Sevana Kasparian,07/25/2007,1,Denver,10,9.700,9.825,9.600,9.700,38.275,https://www.instagram.com/sevanakasparian2025/,NaN,Gymnastics Olympica,CA,2025,2025,USA,False
3,Mckenzie Matters,01/08/2007,7,Alabama,10,9.800,9.700,9.725,9.825,39.000,https://www.instagram.com/mckenzie.matters_2025/,https://www.instagram.com/mckenzie.matters/,Prestige,PA,2024,2025,USA,False
4,Addison Bare,10/10/2006,7,Arkansas,10,9.675,9.725,9.700,9.650,38.575,https://www.instagram.com/addisonbare.gym2025/,https://www.instagram.com/addisonbaree/,Prestige,PA,2024,2025,USA,False

In [36]:
## start rating gymnasts

In [38]:
df_all['Rating'] = (
    0.25 * df_all['VT High'] +
    0.25 * df_all['UB High'] +
    0.25 * df_all['BB High'] +
    0.25 * df_all['FX High']
)

In [39]:
df_all['HasPerfect10'] = df_all[['VT High', 'UB High', 'BB High', 'FX High']].eq(10.0).any(axis=1)
df_all['Rating'] += df_all['HasPerfect10'].astype(int)  # +1 if True

In [40]:
df_all.sort_values(by='Rating', ascending=False).head(10)

,Athlete,DOB,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State,Year,Class,Country,IsElite,Rating,HasPerfect10
451,Faye Rodio,12/30/2005,C,Towson,NaN,9.200,8.925,9.475,36.150,NaN,https://www.instagram.com/fayerodio/,NaN,Bull City (NC)/ Alabama,NaN,NaN,2025,International,False,15.93750,False
40,Allison Cucci,08/07/2007,4,Arkansas,10,10.000,9.925,9.950,9.875,38.975,https://www.instagram.com/allison_cucci2025/,https://www.instagram.com/allisoncucci/,Twin City,MN,2024,2025,USA,False,10.93750,True
2903,Presley Duke,11/08/2007,3,Oklahoma,10,9.900,10.000,9.900,9.925,39.325,https://www.instagram.com/presleyduke2026/,https://www.instagram.com/presleyyduke/,Dynamo,OK,2025,2026,USA,False,10.93125,True
7,Kamila Pawlak,01/16/2007,3,Oklahoma,10,10.000,9.975,9.800,9.925,39.075,https://www.instagram.com/kamilap2025_gymnastics/,https://www.instagram.com/kamilap_2025/,Metroplex,TX,2024,2025,USA,False,10.92500,True
47,Haley Mustari,01/18/2007,3,LSU,10,9.725,10.000,10.000,9.800,39.100,https://www.instagram.com/haley_mustari_2025/,https://www.instagram.com/haley_mustari/,Dynamo,OK,2025,2025,USA,False,10.88125,True
2895,CaMarah Williams,12/26/2007,4,Georgia,Elite,10.000,9.775,9.775,9.975,39.100,https://www.instagram.com/camarahh/,NaN,Edge Riverside,MO,2025,2026,USA,True,10.88125,True
4133,Madyson Boyd,12/09/2008,8,Uncommitted,10,9.875,9.825,9.750,10.000,39.075,https://www.instagram.com/mady_.boyd27/,NaN,Brandy Johnson's,FL,2025,2027,USA,False,10.86250,True
4385,Galilee Vestnys,04/01/2009,1,Uncommitted,10,10.000,9.850,9.650,9.875,39.125,https://www.instagram.com/galileevestnys2027/,https://www.instagram.com/gal_vestnys/,Redwood Empire,CA,2025,2027,USA,False,10.84375,True
2918,Emerson Gaa,04/08/2008,3,Denver,10,9.750,9.875,9.650,10.000,39.100,https://www.instagram.com/emersongaagym_26/,https://www.instagram.com/emerson.m.gaa/,Empire,TX,2025,2026,USA,False,10.81875,True
2889,Addison Sarisky,10/12/2007,5,Alabama,10,9.800,10.000,9.700,9.725,39.050,https://www.instagram.com/addiesarisky2026/,https://www.instagram.com/addiesarisky/,Olympic Dreams,OH,2025,2026,USA,False,10.80625,True

In [41]:
df_all = df_all[df_all['Athlete'] != 'Faye Rodio']

In [42]:
df_all.head()

,Athlete,DOB,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State,Year,Class,Country,IsElite,Rating,HasPerfect10
0,Merideth Brandt,04/08/2007,6,Nebraska,10,NaN,NaN,NaN,NaN,NaN,https://www.instagram.com/meridethbrandtgymnas...,https://www.instagram.com/merideth.brandt/,Yellow Jackets,MA,2024,2025,USA,False,NaN,False
1,Shyla Bhatia,07/02/2007,7,Denver,10,9.775,9.575,9.425,9.850,38.350,https://www.instagram.com/shylabhatia2025/,https://www.instagram.com/missy_miss_demeaner/,Silvia's,PA,2024,2025,USA,False,9.65625,False
2,Sevana Kasparian,07/25/2007,1,Denver,10,9.700,9.825,9.600,9.700,38.275,https://www.instagram.com/sevanakasparian2025/,NaN,Gymnastics Olympica,CA,2025,2025,USA,False,9.70625,False
3,Mckenzie Matters,01/08/2007,7,Alabama,10,9.800,9.700,9.725,9.825,39.000,https://www.instagram.com/mckenzie.matters_2025/,https://www.instagram.com/mckenzie.matters/,Prestige,PA,2024,2025,USA,False,9.76250,False
4,Addison Bare,10/10/2006,7,Arkansas,10,9.675,9.725,9.700,9.650,38.575,https://www.instagram.com/addisonbare.gym2025/,https://www.instagram.com/addisonbaree/,Prestige,PA,2024,2025,USA,False,9.68750,False

In [43]:
df_all.sort_values(by='Rating', ascending=False).head(10)

,Athlete,DOB,Region,School,Level,VT High,UB High,BB High,FX High,AA High,gym insta,personal insta,Club Gym,State,Year,Class,Country,IsElite,Rating,HasPerfect10
40,Allison Cucci,08/07/2007,4,Arkansas,10,10.000,9.925,9.950,9.875,38.975,https://www.instagram.com/allison_cucci2025/,https://www.instagram.com/allisoncucci/,Twin City,MN,2024,2025,USA,False,10.93750,True
2903,Presley Duke,11/08/2007,3,Oklahoma,10,9.900,10.000,9.900,9.925,39.325,https://www.instagram.com/presleyduke2026/,https://www.instagram.com/presleyyduke/,Dynamo,OK,2025,2026,USA,False,10.93125,True
7,Kamila Pawlak,01/16/2007,3,Oklahoma,10,10.000,9.975,9.800,9.925,39.075,https://www.instagram.com/kamilap2025_gymnastics/,https://www.instagram.com/kamilap_2025/,Metroplex,TX,2024,2025,USA,False,10.92500,True
47,Haley Mustari,01/18/2007,3,LSU,10,9.725,10.000,10.000,9.800,39.100,https://www.instagram.com/haley_mustari_2025/,https://www.instagram.com/haley_mustari/,Dynamo,OK,2025,2025,USA,False,10.88125,True
2895,CaMarah Williams,12/26/2007,4,Georgia,Elite,10.000,9.775,9.775,9.975,39.100,https://www.instagram.com/camarahh/,NaN,Edge Riverside,MO,2025,2026,USA,True,10.88125,True
4133,Madyson Boyd,12/09/2008,8,Uncommitted,10,9.875,9.825,9.750,10.000,39.075,https://www.instagram.com/mady_.boyd27/,NaN,Brandy Johnson's,FL,2025,2027,USA,False,10.86250,True
4385,Galilee Vestnys,04/01/2009,1,Uncommitted,10,10.000,9.850,9.650,9.875,39.125,https://www.instagram.com/galileevestnys2027/,https://www.instagram.com/gal_vestnys/,Redwood Empire,CA,2025,2027,USA,False,10.84375,True
2918,Emerson Gaa,04/08/2008,3,Denver,10,9.750,9.875,9.650,10.000,39.100,https://www.instagram.com/emersongaagym_26/,https://www.instagram.com/emerson.m.gaa/,Empire,TX,2025,2026,USA,False,10.81875,True
2889,Addison Sarisky,10/12/2007,5,Alabama,10,9.800,10.000,9.700,9.725,39.050,https://www.instagram.com/addiesarisky2026/,https://www.instagram.com/addiesarisky/,Olympic Dreams,OH,2025,2026,USA,False,10.80625,True
3020,Raeya Linton,02/29/2008,7,Stanford,10,10.000,9.375,9.850,9.950,38.400,https://www.instagram.com/r.n.rae/,NaN,United Gymnastix,MD,2025,2026,USA,False,10.79375,True

In [45]:
df_all.to_csv("cleaned_data.csv", index=False)